### ISSUE TITLE
Perception Node : add_on_set_parameters_callback

### ISSUE THREAD

**Issue by prajwalthakur** [ForzaETH/race_stack#12]
Hi,
where's the function [add_on_set_parameters_callback] (https://github.com/ForzaETH/race_stack/blob/6ba88365188c723efe27fd37ce24feb09e0352a1/perception/perception/detect.py#L164)
is defined in the repository?

**Comment by niciBume** [comment]
Hi there,

This is an rclpy function [here](https://github.com/ros2/rclpy/blob/jazzy/rclpy/rclpy/node.py#L1088). So it is not defined within this repo. This is meant to catch every update on a ROS parameter.

Hope this helps!
