### ISSUE TITLE
Question About LaserPointOnTrack Function 

### ISSUE THREAD

**Issue by prajwalthakur** [ForzaETH/race_stack#13]
Hi,  wanted to ask about the following line in detect.py
[laserPointOnTrack](https://github.com/ForzaETH/race_stack/blob/6ba88365188c723efe27fd37ce24feb09e0352a1/perception/perception/detect.py#L321)
why are we comparing the d ( lateral distance of the obstacle from centerline ?) from the negative of the lateral distance of the right boundary? shouldn't it be something like following :
`d>=  self.d_left_array[idx] or d <= self.d_right_array[idx] :`  . given d is signed-distance and  being negative means (right side of the center ) and positive means left side of the center of the track .
Thanks

**Comment by niciBume** [comment]
Hi there,

As you correctly mention, everything to the right of the reference line (the racing line in our case) has a negative d coordinate. However, `self.d_left_array` is populated without a sign. Hence if you want to check if something is on the track, you need to compare it with the sign, or compare it with the absolute of `d`. 

Have you observed an error with this function? Or is this just a curiosity?

**Comment by prajwalthakur** [comment]
hi .
"However, self.d_left_array is populated without a sign." Ig you mean self.d_right_array is populated without a sign? That's why we multiply it by negative sign so that we can compare it with (d) , here d however is a signed-distance , ( right of the reference will have negative d values) ?
No , I have not encountered any error , I am  trying to understand the perception stack by myself.

**Comment by eghignone** [comment]
Yes both are without a sign, I can also confirm that the track boundaries, as generally obtained from the waypoints message, are unsigned as they are "distances from the boundaries" (legacy from the original optimizer)

In case you have other questions on the LaserPointOnTrack or similar, do not hesitate to ask! Otherwise feel free to close the issue :racing_car: :racing_car: :racing_car:
